version: "3.8"
services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - 80:3000
    networks:
      - a

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - a
      - b

  fastapi:
    build:
      context: ./OAuth
      dockerfile: Dockerfile
    # command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./.env
    ports:
      - 8000:8000
    # volumes:
    # - ./app:/gst/app/
    depends_on:
      - db
    networks:
      - a
      - b
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - TZ=Asia/Kolkata
      # - POSTGRES_PASSWORD = postgres
    env_file:
      - ./.env
    ports:
      - 5432:5432
    networks:
      - b

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: "dracula"

networks:
  a:
  b:

volumes:
  postgres_data:
