import Head from "next/head";
import Editor from "@monaco-editor/react";
import { useEffect, useRef, useState } from "react";
import axios from "axios";

export default function Home() {
  const editorRef = useRef(null);

  const [result, setResult] = useState("");
  const [language, setLanguage] = useState("python");

  const handleEditorDidMount = (editor, monaco) => {
    editorRef.current = editor;
  };

  const showValue = () => {
    console.log(editorRef.current.getValue());
  };

  const handleSubmit = async () => {
    try {
      const response = await axios.post("http://localhost:5000/compile", {
        language,
        code: editorRef.current.getValue(),
      });

      setResult(response.data.result);
    } catch (err) {
      console.log(err);
    }
  };

  return (
    <div className="bg-bgPrimary min-h-screen ">
      <Head>
        <title>Run Code</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex">
        <div>
          <Editor
            height="80vh"
            width={"70vw"}
            theme="vs-dark"
            onMount={handleEditorDidMount}
            defaultLanguage="cpp"
            defaultValue="#Some comment"
          />
          <div className="flex gap-x-10 w-[70vw]">
            <div className="w-[20vw] gap-y-5 flex flex-col">
              <select
                className="px-5 py-3 rounded-lg focus:border"
                onChange={(event) => {
                  setLanguage(event.target.value);
                }}
              >
                <option value={"python"}>Python</option>
                <option value={"cpp"}>C++</option>
                <option value={"javascript"}>Javascript</option>
              </select>
              <div className="mx-auto">
                <button
                  className="gradientBg font-bold text-xl text-white px-8 py-4 rounded-3xl shadow-lg shadow-cyan-200/10"
                  onClick={showValue}
                >
                  Show Value
                </button>
              </div>
            </div>
          </div>
        </div>
        <div className="w-full mx-3">
          <div className=" min-h-screen flex-1 text-white">
            <h1 className="text-3xl font-bold mx-5 my-2 gradientText">
              Output:
            </h1>
            <div className="bg-neutral-900 min-h-[50vh] rounded-xl px-5 py-2">
              {result.split("\n").map((item, index) => {
                return (
                  <p className="font-mono font-semibold" key={index}>
                    {item}
                  </p>
                );
              })}
              <p className="font-mono font-semibold">Hello world</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
