import Head from "next/head";
import Editor from "@monaco-editor/react";
import { useRef } from "react";

export default function Home() {
  const editorRef = useRef(null);
  const handleEditorDidMount = (editor, monaco) => {
    editorRef.current = editor;
  };
  const showValue = () => {
    console.log(editorRef.current.getValue());
  };
  return (
    <div>
      <Head>
        <title>Compiler Project X</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={showValue}>Show Value</button>
      <Editor
        height="90vh"
        onMount={handleEditorDidMount}
        defaultLanguage="cpp"
        defaultValue="//some comment"
      />
    </div>
  );
}
