version: '3.8'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    # command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./.env
    ports:
      - 8000:8000
    volumes:
      - ./app:/gst/app/
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - TZ=Asia/Kolkata
      # - POSTGRES_PASSWORD = postgres
    env_file:
      - ./.env
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
            ADMINER_DESIGN: 'dracula'



volumes:
    postgres_data: